# Generated by Django 5.2.4 on 2025-12-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hokhau', '0001_initial'),
        ('noptien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noptien',
            name='hokhau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hokhau.hokhau'),
        ),
    ]
