# Generated by Django 6.0 on 2025-12-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hokhau', '0001_initial'),
        ('noptien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noptien',
            name='hokhau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hokhau.hokhau'),
        ),
        migrations.AlterField(
            model_name='noptien',
            name='ngaynop',
            field=models.DateField(blank=True, null=True),
        ),
    ]
