# Generated by Django 5.2.4 on 2025-12-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noptien', '0002_alter_noptien_hokhau'),
        ('noptien', '0002_alter_noptien_hokhau_alter_noptien_ngaynop'),
    ]

    operations = [
    ]
