# Generated by Django 6.0 on 2025-12-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_date_joined_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vaitro',
            field=models.CharField(choices=[('admin', 'Tổ trưởng/Tổ phó'), ('canbo', 'Cán bộ'), ('ketoan', 'Kế toán'), ('user', 'Người dùng')], default='user', max_length=50, verbose_name='Vai trò'),
        ),
    ]
