# Generated by Django 6.0 on 2025-12-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hokhau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hokhau',
            name='ghichu',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
    ]
