# Generated by Django 5.2.4 on 2025-11-23 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhankhau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamTruTamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangthai', models.CharField(max_length=20)),
                ('diachitamtrutamvang', models.CharField(max_length=200)),
                ('thoigian', models.DateField()),
                ('noidungdenghi', models.TextField(blank=True, null=True)),
                ('nhankhau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nhankhau.nhankhau')),
            ],
        ),
    ]
