# Generated by Django 5.2.8 on 2025-12-22 08:14

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('tamtrutamvang', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
