# Generated by Django 5.2.4 on 2025-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhoanThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhoanthu', models.CharField(max_length=100)),
                ('ngaytao', models.DateField()),
                ('thoihan', models.DateField()),
                ('batbuoc', models.BooleanField(default=False)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('sotien', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
